apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u8v2t0lfg-python
  janus-idp.io/tekton: u8v2t0lfg-python
  backstage.io/kubernetes-id: u8v2t0lfg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u8v2t0lfg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
