apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u8v2t0lfg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u8v2t0lfg-python 
  name: u8v2t0lfg-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u8v2t0lfg-python 
